theme: minima
title: Github Page Is An Amazing Tool
author: Jallow
email: bailo.jallow@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  i am totally amazed by the github page functionalities

# social links
#twitter_username: your-twitter-handle
github_username:  mbjallow6

show_excerpts: true # set to false to remove excerpts on the homepage
